// <auto-generated />
namespace FootballManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class June9th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(June9th));
        
        string IMigrationMetadata.Id
        {
            get { return "202006091831060_June9th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
